//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopgiayonline.Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLShoesEntities : DbContext
    {
        public QLShoesEntities()
            : base("name=QLShoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAI> LOAIs { get; set; }
        public virtual DbSet<QUANTRI> QUANTRIs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual ObjectResult<Nullable<bool>> sp_Account_Login(string userAdmin, string matKhauAdmin)
        {
            var userAdminParameter = userAdmin != null ?
                new ObjectParameter("UserAdmin", userAdmin) :
                new ObjectParameter("UserAdmin", typeof(string));
    
            var matKhauAdminParameter = matKhauAdmin != null ?
                new ObjectParameter("MatKhauAdmin", matKhauAdmin) :
                new ObjectParameter("MatKhauAdmin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_Account_Login", userAdminParameter, matKhauAdminParameter);
        }
    
        public virtual ObjectResult<sp_ChiTietDonHang_Result> sp_ChiTietDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietDonHang_Result>("sp_ChiTietDonHang");
        }
    }
}
